Add-Type -AssemblyName System.Drawing

$static = Join-Path $PSScriptRoot "static"

function New-FaviconPng {
    param([int]$Size, [string]$OutPath)
    $bmp = New-Object System.Drawing.Bitmap($Size, $Size)
    $g = [System.Drawing.Graphics]::FromImage($bmp)
    $g.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::AntiAlias
    $g.TextRenderingHint = [System.Drawing.Text.TextRenderingHint]::AntiAliasGridFit
    $g.Clear([System.Drawing.Color]::Transparent)

    # 鍦嗚鑳屾櫙
    $bg = New-Object System.Drawing.SolidBrush([System.Drawing.Color]::FromArgb(255, 15, 15, 15))  # #2563EB
    $radius = [int]($Size * 0.22)
    $rect = New-Object System.Drawing.Rectangle(0, 0, $Size, $Size)
    $path = New-Object System.Drawing.Drawing2D.GraphicsPath
    $d = $radius * 2
    $path.AddArc($rect.X, $rect.Y, $d, $d, 180, 90)
    $path.AddArc($rect.X + $rect.Width - $d, $rect.Y, $d, $d, 270, 90)
    $path.AddArc($rect.X + $rect.Width - $d, $rect.Y + $rect.Height - $d, $d, $d, 0, 90)
    $path.AddArc($rect.X, $rect.Y + $rect.Height - $d, $d, $d, 90, 90)
    $path.CloseFigure()
    $g.FillPath($bg, $path)

    # "TB" 鏂囧瓧
    $fontSize = $Size * 0.46
    $font = New-Object System.Drawing.Font("Segoe UI", $fontSize, [System.Drawing.FontStyle]::Bold, [System.Drawing.GraphicsUnit]::Pixel)
    $fg = New-Object System.Drawing.SolidBrush([System.Drawing.Color]::FromArgb(255, 255, 107, 26))
    $fmt = New-Object System.Drawing.StringFormat
    $fmt.Alignment = [System.Drawing.StringAlignment]::Center
    $fmt.LineAlignment = [System.Drawing.StringAlignment]::Center
    $txtRect = New-Object System.Drawing.RectangleF(0, -($Size * 0.02), $Size, $Size)
    $g.DrawString("TB", $font, $fg, $txtRect, $fmt)

    $g.Dispose()
    $bmp.Save($OutPath, [System.Drawing.Imaging.ImageFormat]::Png)
    $bmp.Dispose()
    Write-Output "PNG_OK $OutPath"
}

New-FaviconPng -Size 16  -OutPath "$static\favicon-16x16.png"
New-FaviconPng -Size 32  -OutPath "$static\favicon-32x32.png"
New-FaviconPng -Size 180 -OutPath "$static\apple-touch-icon.png"


# ICO 由 make-ico.py 生成（标准 Vista+ 格式，内嵌 PNG）

# ICO is generated by make-ico.py (standard Vista+ format, embeds PNG)
